type: huggingface_clip_vision
models:
  - name: _pretrained_
    path: openai/clip-vit-base-patch32

dataset_type: huggingface_image_classification
train_datasets:
  - name: gtsrb
    dataset:
      name: tanganke/gtsrb
      split: train